version: "3.8" 

services:
  elasticsearch1:
    image: elasticsearch:8.13.4
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - xpack.monitoring.exporters.remote.type=http
      - xpack.monitoring.exporters.remote.host=monitor
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  elasticsearch2:
    image: elasticsearch:8.13.4
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - xpack.monitoring.exporters.remote.type=http
      - xpack.monitoring.exporters.remote.host=monitor
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - xpack.security.enabled=false
    ports:
      - "9201:9200"



  kibana-devtools:
    image: kibana:8.13.4
    container_name: kibana-devtools
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch1:9200
    ports:
      - "5601:5601"

