version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "MghRabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      # - RABBITMQ_DEFAULT_VHOST=my_vhost

#    volumes:
#      - c:/volume/rabbitmq/data/:/var/lib/rabbitmq/
#      - c:/volume/rabbitmq/data/log/:/var/log/rabbitmq

    hostname: my-rabbit

    networks:
      - MghRabbitNetwork
networks:
  MghRabbitNetwork:
    name: MghRabbitNetwork
    driver: bridge
    external: false
