version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

# Optional if you'd like a custom configuration file.
# This file can include options like `requirepass` and `timeout`.
# Make sure this redis.conf is created in the same directory as this docker-compose file.

# Content of redis.conf:
# requirepass 123456
# bind 127.0.0.1
# timeout 100
# tcp-keepalive 0
# databases 1
