version: '3.8'

services:
  # # SQL Server
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sqlserver
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=@Mgh2071qaz
  #     - TZ=Iran/Tehran
  #   shm_size: 1g
  #   hostname: sql22
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - c:/volumes/sqlserver/data:/var/opt/mssql/data
  #   networks:
  #     - localnetwork

  # PostgreSQL    
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maintenance_db
    ports:
      - "5432:5432"
    volumes:
      - c:/volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - localnetwork

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    volumes:
      - c:/volumes/rabbitmq/data:/var/lib/rabbitmq/
      - c:/volumes/rabbitmq/data/log:/var/log/rabbitmq
    hostname: my-rabbit
    networks:
      - localnetwork

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6379:6379"
    networks:
      - localnetwork
    volumes:
      - redis-data:/data

  # Elasticsearch Nodes
  elasticsearch1:
    image: elasticsearch:8.13.4
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
    networks:
      - localnetwork

  elasticsearch2:
    image: elasticsearch:8.13.4
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ports:
      - "9201:9200"
    networks:
      - localnetwork

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"     
      - "443:443"    
    # volumes:
    #   - /c/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf   # Ensure it's a file, not a directory and it should be exist
    #   - /c/volumes/nginx/html:/usr/share/nginx/html      
    networks:
      - localnetwork
    restart: always

networks:
  localnetwork:
    driver: bridge

volumes:
  redis-data:
